//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace elnökök
{
    using System;
    using System.Collections.Generic;
    
    public partial class elnokok
    {
        public int RowNumber { get; set; }
        public string Id { get; set; }
        public string Name { get; set; }
        public string birth { get; set; }
        public string death { get; set; }
        public string presidency { get; set; }
        public string good_1 { get; set; }
        public string good_2 { get; set; }
        public string good_3 { get; set; }
        public string bad_1 { get; set; }
        public string bad_2 { get; set; }
        public string bad_3 { get; set; }
        public string funfact { get; set; }
        public string kep { get; set; }
    }
}
